// PRD v1.3, Sec 2.2 & 7: PWA Finalization

// This configuration assumes you have `next-pwa` installed.
// npm install next-pwa

const withPWA = require('next-pwa')({
  dest: 'public',
  register: true,
  skipWaiting: true,
  disable: process.env.NODE_ENV === 'development',
  // PRD Sec 2.2: Stubbing IndexedDB logic for offline script editing
  // The service worker generated by next-pwa can cache pages, but for
  // dynamic data like script editing, we need a client-side solution.
  // The Zustand persist middleware is the chosen tool for this.
  // We will implement this in the relevant Zustand store, e.g., `useCampaignStore.ts`
  // Example (to be placed in the store):
  //
  // import { create } from 'zustand';
  // import { persist, createJSONStorage } from 'zustand/middleware';
  // 
  // export const useCampaignStore = create(
  //   persist(
  //     (set, get) => ({
  //       scripts: {},
  //       updateScript: (campaignId, scriptContent) => set(state => ({ ... })),
  //       // sync with backend when online
  //     }),
  //     {
  //       name: 'campaign-storage', // unique name
  //       storage: createJSONStorage(() => localStorage), // or indexedDB via a helper
  //     }
  //   )
  // );
});

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  // any other existing nextjs config
};

module.exports = withPWA(nextConfig);
