import { AuthGate } from '../components/AuthProvider';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AuthGate>
          {children}
        </AuthGate>
      </body>
    </html>
  )
}
