import Header from '../components/Header';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main style={{ maxWidth: 1120, margin: "24px auto", padding: "0 16px" }}>
          {children}
        </main>
      </body>
    </html>
  )
}